In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')

df

FirstName LastName   Age  Sex preTestScore postTestScore location
0       abc      mno  12.0    m         90.0          65.0      NaN
1       NaN      NaN   NaN  NaN         90.0             ?      NaN
2       ghi      pqr  12.0    f            -          65.0        ?
3       jkl      stu  12.0    f         90.0          62.0      NaN
4       mno      vwx  12.0    m         89.0          63.0      NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FirstName      4 non-null      object 
 1   LastName       4 non-null      object 
 2   Age            4 non-null      float64
 3   Sex            4 non-null      object 
 4   preTestScore   5 non-null      object 
 5   postTestScore  5 non-null      object 
 6   location       1 non-null      object 
dtypes: float64(1), object(6)
memory usage: 412.0+ bytes


In [5]:
missing_values = [ 'n/a', '-', '?' ]

df = pd.read_csv('data.csv', na_values=missing_values)

df

FirstName LastName   Age  Sex  preTestScore  postTestScore  location
0       abc      mno  12.0    m          90.0           65.0       NaN
1       NaN      NaN   NaN  NaN          90.0            NaN       NaN
2       ghi      pqr  12.0    f           NaN           65.0       NaN
3       jkl      stu  12.0    f          90.0           62.0       NaN
4       mno      vwx  12.0    m          89.0           63.0       NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FirstName      4 non-null      object 
 1   LastName       4 non-null      object 
 2   Age            4 non-null      float64
 3   Sex            4 non-null      object 
 4   preTestScore   4 non-null      float64
 5   postTestScore  4 non-null      float64
 6   location       0 non-null      float64
dtypes: float64(4), object(3)
memory usage: 412.0+ bytes


In [7]:
df.isnull()

FirstName  LastName    Age    Sex  preTestScore  postTestScore  location
0      False     False  False  False         False          False      True
1       True      True   True   True         False           True      True
2      False     False  False  False          True          False      True
3      False     False  False  False         False          False      True
4      False     False  False  False         False          False      True

In [8]:
df.isnull().sum()

FirstName        1
LastName         1
Age              1
Sex              1
preTestScore     1
postTestScore    1
location         5
dtype: int64

In [13]:
df.isnull().any(axis=0)

FirstName        True
LastName         True
Age              True
Sex              True
preTestScore     True
postTestScore    True
location         True
dtype: bool

In [15]:
df.isnull().all(axis=0)

FirstName        False
LastName         False
Age              False
Sex              False
preTestScore     False
postTestScore    False
location          True
dtype: bool

In [16]:
df.isnull().all(axis=0).sum()

np.int64(1)

In [17]:
df.isnull().all(axis=1)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [19]:
#calculating the percent of null values for each column
(df.isnull().sum()/len(df.index)) * 100

FirstName         20.0
LastName          20.0
Age               20.0
Sex               20.0
preTestScore      20.0
postTestScore     20.0
location         100.0
dtype: float64

In [ ]:
#the location has 100%, which means that the entire column is made up of null values
#removing the location column
df.dropna(axis=1, how='all', inplace=True)
df

FirstName LastName   Age  Sex  preTestScore  postTestScore
0       abc      mno  12.0    m          90.0           65.0
1       NaN      NaN   NaN  NaN          90.0            NaN
2       ghi      pqr  12.0    f           NaN           65.0
3       jkl      stu  12.0    f          90.0           62.0
4       mno      vwx  12.0    m          89.0           63.0

In [27]:
# Missing values treatment in rows - Removing rows
df[df.isnull().sum(axis=1)>=4]



FirstName LastName  Age  Sex  preTestScore  postTestScore
1       NaN      NaN  NaN  NaN          90.0            NaN

In [30]:
#retaining the rows having <=4 NaNs

df = df[df.isnull().sum(axis=1) <= 4]
df

FirstName LastName   Age Sex  preTestScore  postTestScore
0       abc      mno  12.0   m          90.0           65.0
2       ghi      pqr  12.0   f           NaN           65.0
3       jkl      stu  12.0   f          90.0           62.0
4       mno      vwx  12.0   m          89.0           63.0

In [31]:
df.describe()

Age  preTestScore  postTestScore
count   4.0      3.000000           4.00
mean   12.0     89.666667          63.75
std     0.0      0.577350           1.50
min    12.0     89.000000          62.00
25%    12.0     89.500000          62.75
50%    12.0     90.000000          64.00
75%    12.0     90.000000          65.00
max    12.0     90.000000          65.00

In [32]:
df['preTestScore'].describe()

count     3.000000
mean     89.666667
std       0.577350
min      89.000000
25%      89.500000
50%      90.000000
75%      90.000000
max      90.000000
Name: preTestScore, dtype: float64

In [34]:
df.loc[:, 'preTestScore'] = df['preTestScore'].fillna(df['preTestScore'].mean())
df

FirstName LastName   Age Sex  preTestScore  postTestScore
0       abc      mno  12.0   m     90.000000           65.0
2       ghi      pqr  12.0   f     89.666667           65.0
3       jkl      stu  12.0   f     90.000000           62.0
4       mno      vwx  12.0   m     89.000000           63.0

In [36]:
df = pd.read_csv('data.csv', na_values=missing_values)

In [39]:
df_num = df.select_dtypes(include=['number'])
df_num

Age  preTestScore  postTestScore  location
0  12.0          90.0           65.0       NaN
1   NaN          90.0            NaN       NaN
2  12.0           NaN           65.0       NaN
3  12.0          90.0           62.0       NaN
4  12.0          89.0           63.0       NaN

In [40]:
df_num2 = df_num.drop(['location'], axis=1)
df_num2

Age  preTestScore  postTestScore
0  12.0          90.0           65.0
1   NaN          90.0            NaN
2  12.0           NaN           65.0
3  12.0          90.0           62.0
4  12.0          89.0           63.0

In [42]:
#explicitly ask for this experimental feature

from sklearn.experimental import enable_iterative_imputer

# then import the library
from sklearn.impute import IterativeImputer

In [48]:
# Initialize it
iterimp = IterativeImputer()

df_iterimp = pd.DataFrame(iterimp.fit_transform(df_num2), columns=df_num2.columns, index=df_num2.index)

df_iterimp

Age  preTestScore  postTestScore
0  12.0     90.000000      65.000000
1  12.0     90.000000      63.750226
2  12.0     89.751133      65.000000
3  12.0     90.000000      62.000000
4  12.0     89.000000      63.000000

In [49]:
#dropping the location column since it contains all null values

iterimp.fit_transform(df_num2)

array([[12.        , 90.        , 65.        ],
       [12.        , 90.        , 63.75022648],
       [12.        , 89.75113289, 65.        ],
       [12.        , 90.        , 62.        ],
       [12.        , 89.        , 63.        ]])

In [57]:
from sklearn.impute import  SimpleImputer

mean_imputer = SimpleImputer(strategy = 'mean')   # median can also be used

df_mean_imp = pd.DataFrame(mean_imputer.fit_transform(df_num2), columns=df_num2.columns, index=df_num2.index)


df_mean_imp

Age  preTestScore  postTestScore
0  12.0         90.00          65.00
1  12.0         90.00          63.75
2  12.0         89.75          65.00
3  12.0         90.00          62.00
4  12.0         89.00          63.00

In [58]:
df_mean_imp.isnull().sum()

Age              0
preTestScore     0
postTestScore    0
dtype: int64

In [59]:
# Mean Imputation
#mean_imputer = SimpleImputer(strategy='mean')

# Median Imputation
#median_imputer = SimpleImputer(strategy='median')

# Most Frequent Imputation
#mode_imputer = SimpleImputer(strategy='most_frequent')

# Constant Imputation
#constant_imputer = SimpleImputer(strategy='constant', fill_value=0)

In [60]:
mean_imputer.fit_transform(df_num2)

array([[12.  , 90.  , 65.  ],
       [12.  , 90.  , 63.75],
       [12.  , 89.75, 65.  ],
       [12.  , 90.  , 62.  ],
       [12.  , 89.  , 63.  ]])

In [65]:
from sklearn.impute import  KNNImputer

knn_imputer = KNNImputer(n_neighbors=3)

df_knn_imp = pd.DataFrame(knn_imputer.fit_transform(df_num2), columns=df_num2.columns, index=df_num2.index)

df_knn_imp

Age  preTestScore  postTestScore
0  12.0     90.000000      65.000000
1  12.0     90.000000      63.333333
2  12.0     89.666667      65.000000
3  12.0     90.000000      62.000000
4  12.0     89.000000      63.000000

In [66]:
knn_imputer.fit_transform(df_num2)

array([[12.        , 90.        , 65.        ],
       [12.        , 90.        , 63.33333333],
       [12.        , 89.66666667, 65.        ],
       [12.        , 90.        , 62.        ],
       [12.        , 89.        , 63.        ]])

In [68]:
from sklearn.impute import  MissingIndicator

x_array = np.array([[-1, -1, 3, 7],
                   [4, 6, 0, -1],
                   [-1, 1, 6,2]])

indicator = MissingIndicator(missing_values=-1)

mask_missing_values_only = indicator.fit_transform(x_array)
mask_missing_values_only

array([[ True,  True, False],
       [False, False,  True],
       [ True, False, False]])

In [ ]:
#to check the columns that were returned
indicator.features_

array([0, 1, 3])

In [70]:
indicator = MissingIndicator(missing_values= -1, features='all')

mask_all = indicator.fit_transform(x_array)
mask_all

array([[ True,  True, False, False],
       [False, False, False,  True],
       [ True, False, False, False]])

In [71]:
indicator.features_

array([0, 1, 2, 3])

In [79]:
from sklearn.impute import  SimpleImputer, MissingIndicator

from sklearn.pipeline import FeatureUnion

transformer = FeatureUnion(transformer_list=[('features', SimpleImputer(strategy='mean')), ('indicator', MissingIndicator())])



results = pd.DataFrame(transformer.fit_transform(df_num2), index=df_num2.index)

results

0      1      2    3    4    5
0  12.0  90.00  65.00  0.0  0.0  0.0
1  12.0  90.00  63.75  1.0  0.0  1.0
2  12.0  89.75  65.00  0.0  1.0  0.0
3  12.0  90.00  62.00  0.0  0.0  0.0
4  12.0  89.00  63.00  0.0  0.0  0.0

In [80]:
results.columns = ['Age', 'preTestScore', 'postTestScore', 'is_null_age', 'is_null_preTest', 'is_null_postTest']
results

Age  preTestScore  postTestScore  is_null_age  is_null_preTest  \
0  12.0         90.00          65.00          0.0              0.0   
1  12.0         90.00          63.75          1.0              0.0   
2  12.0         89.75          65.00          0.0              1.0   
3  12.0         90.00          62.00          0.0              0.0   
4  12.0         89.00          63.00          0.0              0.0   

   is_null_postTest  
0               0.0  
1               1.0  
2               0.0  
3               0.0  
4               0.0