In [ ]:
%load_ext rpy2.ipython




The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


In [ ]:
%%R
summary(cars)

     speed           dist       
 Min.   : 4.0   Min.   :  2.00  
 1st Qu.:12.0   1st Qu.: 26.00  
 Median :15.0   Median : 36.00  
 Mean   :15.4   Mean   : 42.98  
 3rd Qu.:19.0   3rd Qu.: 56.00  
 Max.   :25.0   Max.   :120.00  


In addition: Warning message:
In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
  libraries ‘/usr/local/lib/R/site-library’, ‘/usr/lib/R/site-library’ contain no packages


In [ ]:
3%%2

[1] 1

In [4]:
3^2

[1] 9

In [7]:
paste("Here we go", "again")

[1] "Here we go again"

In [12]:
paste("look", "here", sep="_")

[1] "look_here"

In [13]:
print("Let's print some R")

[1] "Let's print some R"


In [ ]:
print("Let's print some R", quote = FALSE)

[1] Let's print some R


In [18]:
noquote("Let's print some R")

[1] Let's print some R

In [20]:
introduction <- "R here!"

print(introduction)

[1] "R here!"


In [22]:
introduction <- "R is here again"

noquote(introduction)

[1] R is here again

In [26]:
men <- 32
women <- 40

Total <- men + women

cat("There are", Total, " people in the meeting")

There are 72  people in the meeting

In [27]:
"meme" == "memo"

[1] FALSE

In [34]:
cats <- 2
dogs <- 4

pets <- cats + dogs

print(pets)

[1] 6


In [35]:
cat("We have", pets, "pets:", cats, "cats and", dogs, "dogs")

We have 6 pets: 2 cats and 4 dogs

In [40]:
length_of_side <- 8

area <- length_of_side^2

perimeter <- length_of_side * 4

cat("Area of the object is", area, "and perimeter is", perimeter)

Area of the object is 64 and perimeter is 32

In [41]:
v1 <- c(1, 2, 3, 4)

print(v1)

[1] 1 2 3 4


In [44]:
v2 <- c("This", "is", "me")
print(v2)

[1] "This" "is"   "me"  


In [45]:
#Mixed data types

v4  <-  c(TRUE, FALSE, TRUE, "FALSE")
print(v4)

[1] "TRUE"  "FALSE" "TRUE"  "FALSE"


In [46]:
seql <- 1:10

print(seql)

 [1]  1  2  3  4  5  6  7  8  9 10


In [48]:
seql2 <- 5:-5

print(seql2)

 [1]  5  4  3  2  1  0 -1 -2 -3 -4 -5


In [1]:
seq(10)

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
seq(1,10,2)

[1] 1 3 5 7 9

In [5]:
seq(1, 10, length = 20)

[1]  1.000000  1.473684  1.947368  2.421053  2.894737  3.368421  3.842105
 [8]  4.315789  4.789474  5.263158  5.736842  6.210526  6.684211  7.157895
[15]  7.631579  8.105263  8.578947  9.052632  9.526316 10.000000

In [7]:
seq(from = 1, to=10, by=0.5)

[1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0

In [9]:
sample(1:20)

[1]  3 17 10  1 18  5 15 20  6 16 11 19  9  4 12 14 13  8  2  7

In [10]:
table(c(20, 30, 40, 20, 20, 20, 40))


20 30 40 
 4  1  2 

In [11]:
numbers <- c(1,2,3,4,5,6,7,8,9,10,11,12) # nolint: commas_linter.

numbers^2

[1]   1   4   9  16  25  36  49  64  81 100 121 144

In [12]:
nums  <- c(1,2,3,4,5,6,7,8,9,10)

nums[(nums < 4) | (nums > 8)]

[1]  1  2  3  9 10

In [1]:
nums <- matrix(1:12, 3, 4)
nums

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [2]:
nums[-3, -1:-2]

[,1] [,2]
[1,] 7    10  
[2,] 8    11

In [8]:
states  <- matrix(21:40, nrow=4)

states

[,1] [,2] [,3] [,4] [,5]
[1,] 21   25   29   33   37  
[2,] 22   26   30   34   38  
[3,] 23   27   31   35   39  
[4,] 24   28   32   36   40

In [9]:
colnames(states) <- c("Mon", "Tue", "Wed", "Thur", "Fri")

states

Mon Tue Wed Thur Fri
[1,] 21  25  29  33   37 
[2,] 22  26  30  34   38 
[3,] 23  27  31  35   39 
[4,] 24  28  32  36   40

In [10]:
rownames(states) <- c("California", "Texas", "Florida", "New York")

states

Mon Tue Wed Thur Fri
California 21  25  29  33   37 
Texas      22  26  30  34   38 
Florida    23  27  31  35   39 
New York   24  28  32  36   40